use mavenmovies;
/*Generate the report  with the followin data 

Get the total revenue generated by India, pakistan,China Customers combined in the category of  horror, Comedy and Family.

*/
SELECT SUM(p.amount) AS total_revenue,
c.name as categoryName
FROM payment AS p
INNER JOIN rental AS r ON p.rental_id = r.rental_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN film AS f ON i.film_id = f.film_id
INNER JOIN film_category AS fc ON f.film_id = fc.film_id
INNER JOIN category AS c ON fc.category_id = c.category_id
INNER JOIN customer AS cu ON r.customer_id = cu.customer_id
INNER JOIN address AS addr ON cu.address_id = addr.address_id
INNER JOIN city AS cit ON addr.city_id = cit.city_id
INNER JOIN country AS cou ON cit.country_id = cou.country_id
WHERE cou.country IN ('India', 'Pakistan', 'China')
AND c.name IN ('Horror', 'Comedy', 'Family')
GROUP BY c.name ;


/*
Get the total number of rental days by country and list the top 3 countries
CountryName, TotalNumberofdays
*/

SELECT
c.country AS CountryName,
SUM(DATEDIFF(r.return_date, r.rental_date)) AS TotalNumberofdays
FROM customer AS cu
INNER JOIN
rental AS r ON cu.customer_id = r.customer_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN film AS f ON i.film_id = f.film_id
INNER JOIN film_category AS fc ON f.film_id = fc.film_id
INNER JOIN category AS cat ON fc.category_id = cat.category_id
INNER JOIN address AS a ON cu.address_id = a.address_id
INNER JOIN city AS cty ON a.city_id = cty.city_id
INNER JOIN country AS c ON cty.country_id = c.country_id
GROUP BY
CountryName
ORDER BY
TotalNumberofdays DESC
LIMIT 3;


SELECT
c.country AS CountryName,
SUM(DATEDIFF(r.return_date, r.rental_date)) AS TotalNumberofdays
FROM customer AS cu
INNER JOIN
rental AS r ON cu.customer_id = r.customer_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN film AS f ON i.film_id = f.film_id
INNER JOIN film_category AS fc ON f.film_id = fc.film_id
INNER JOIN category AS cat ON fc.category_id = cat.category_id
INNER JOIN address AS a ON cu.address_id = a.address_id
INNER JOIN city AS cty ON a.city_id = cty.city_id
INNER JOIN country AS c ON cty.country_id = c.country_id
GROUP BY
CountryName
ORDER BY
TotalNumberofdays DESC
LIMIT 3;


