--2. Find the total revenue generated by store1.
SELECT SUM(p.amount) AS total_revenue
FROM payment AS p
INNER JOIN  rental AS r ON p.rental_id = r.rental_id
INNER JOIN inventory AS i ON r.inventory_id = i.inventory_id
INNER JOIN store AS s ON i.store_id = s.store_id
WHERE s.store_id = 1;